package com.como.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKitForEduApi.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKitForEduApi {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("edu_user", "id", EduUser.class);
	}
}

