package com.como.model;

import com.como.model.base.BaseEduUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EduUser extends BaseEduUser<EduUser> {
	public static final EduUser dao = new EduUser().dao();

	public EduUser findByOpenId(String openId) {
		String sql = "select * from hm_user t where t.openId=?";
		return super.findFirst(sql, openId);
	}

	public EduUser findByUserId(long userId){
		String sql = "select *,DATE_FORMAT(t.birthDay,'%Y-%m-%d') AS birthDayStr from hm_user t where t.id = ?";
		return super.findFirst(sql,userId);
	}
}
