package com.como.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseHmUser<M extends BaseHmUser<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setNickName(String nickName) {
		set("nickName", nickName);
		return (M)this;
	}

	public String getNickName() {
		return getStr("nickName");
	}

	public M setRealName(String realName) {
		set("realName", realName);
		return (M)this;
	}

	public String getRealName() {
		return getStr("realName");
	}

	public M setAvatar(String avatar) {
		set("avatar", avatar);
		return (M)this;
	}

	public String getAvatar() {
		return getStr("avatar");
	}

	public M setGender(Integer gender) {
		set("gender", gender);
		return (M)this;
	}

	public Integer getGender() {
		return getInt("gender");
	}

	public M setPassword(String password) {
		set("password", password);
		return (M)this;
	}

	public String getPassword() {
		return getStr("password");
	}

	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public String getMobile() {
		return getStr("mobile");
	}

	public M setBirthDay(java.util.Date birthDay) {
		set("birthDay", birthDay);
		return (M)this;
	}

	public java.util.Date getBirthDay() {
		return get("birthDay");
	}

	public M setRegTime(java.util.Date regTime) {
		set("regTime", regTime);
		return (M)this;
	}

	public java.util.Date getRegTime() {
		return get("regTime");
	}

	public M setLanguage(String language) {
		set("language", language);
		return (M)this;
	}

	public String getLanguage() {
		return getStr("language");
	}

	public M setCity(String city) {
		set("city", city);
		return (M)this;
	}

	public String getCity() {
		return getStr("city");
	}

	public M setProvince(String province) {
		set("province", province);
		return (M)this;
	}

	public String getProvince() {
		return getStr("province");
	}

	public M setCountry(String country) {
		set("country", country);
		return (M)this;
	}

	public String getCountry() {
		return getStr("country");
	}

	public M setOpenId(String openId) {
		set("openId", openId);
		return (M)this;
	}

	public String getOpenId() {
		return getStr("openId");
	}

	public M setUnionId(String unionId) {
		set("unionId", unionId);
		return (M)this;
	}

	public String getUnionId() {
		return getStr("unionId");
	}

}
