package com.como.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseEduUser<M extends BaseEduUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setNickName(java.lang.String nickName) {
		set("nickName", nickName);
		return (M)this;
	}
	
	public java.lang.String getNickName() {
		return getStr("nickName");
	}

	public M setRealName(java.lang.String realName) {
		set("realName", realName);
		return (M)this;
	}
	
	public java.lang.String getRealName() {
		return getStr("realName");
	}

	public M setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
		return (M)this;
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}

	public M setGender(java.lang.Integer gender) {
		set("gender", gender);
		return (M)this;
	}
	
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setBirthDay(java.util.Date birthDay) {
		set("birthDay", birthDay);
		return (M)this;
	}
	
	public java.util.Date getBirthDay() {
		return get("birthDay");
	}

	public M setRegTime(java.util.Date regTime) {
		set("regTime", regTime);
		return (M)this;
	}
	
	public java.util.Date getRegTime() {
		return get("regTime");
	}

	public M setLanguage(java.lang.String language) {
		set("language", language);
		return (M)this;
	}
	
	public java.lang.String getLanguage() {
		return getStr("language");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public M setCountry(java.lang.String country) {
		set("country", country);
		return (M)this;
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setUnionId(java.lang.String unionId) {
		set("unionId", unionId);
		return (M)this;
	}
	
	public java.lang.String getUnionId() {
		return getStr("unionId");
	}

}
